### ISSUE TITLE
HMR is not working in container

### ISSUE THREAD

**Issue by ABQJuan** [patrickleet/streaming-ssr-react-styled-components#1]
I'm on a Windows 10 machine using WSL for the make utility. Everything works outside the container but not when I run`make dev`

**Comment by slaterbbx** [comment]
Hey, I think that this may be the issue here https://github.com/patrickleet/streaming-ssr-react-styled-components/pull/2 Can't say 100% but let me know if that was the issue.

**Comment by slaterbbx** [comment]
Hey man, He patched it with that update, do a pull and see if that fixed it for you. @ABQJuan

**Comment by ABQJuan** [comment]
Ok. It'll probably will be in a couple of days, but I'll test it and reply back with my results. Thanks!

**Comment by slaterbbx** [comment]
Awesome, the more I think about it the more I doubt that is your issue. Because in the docker container it really shouldn't matter about having a single or double quote in the node commands, Linux rarely has such quirks. But I am curious so thanks 👍

**Comment by patrickleet** [comment]
If you are switching back and forth between developing locally and in the container you need to delete node_modules - this could be avoided with a combination of external docker volumes. Sorry without more information about how it doesn't work I'm basically just guessing. Maybe you could record a screencast?

**Comment by slaterbbx** [comment]
If that's the case, maybe you could use volumes and install node modules in the docker container and just not copy over the node_modules from your local env.

```yaml
volumes:
      - /app/node_modules
      - ./:/app
```
**The above is not related to the project just an example:**
The above code should copy everything over from your ./ "root" folder to the ./app in your container and then that will only use the local node_modules for local dev and a separate node_modules while in the container. This way, if you want that kind of "Swap back and forth" workflow, the compiled node_modules that compile dif on linux vs windows shouldn't give you issues.

If that does not make sense, let me know and I will orient it to this project.

**Comment by patrickleet** [comment]
needs to be external volume cause it's shared between builder and running container

**Comment by patrickleet** [comment]
like so: https://github.com/patrickleet/streaming-ssr-react-styled-components/commit/a0e1c28af5bc280c07faf6af426468a547d8c74d

**Comment by patrickleet** [comment]
still unclear if this was the issue...

**Comment by patrickleet** [comment]
@ABQJuan I changed something for you lol - not sure if it's related to your problem for lack of details - feel free to open a new ticket if it doesn't address your needs.
